### ISSUE TITLE
Support building on Windows, macOS

### ISSUE THREAD

**Issue by awerchniak** [awerchniak/cdk-hiscores-tracker#8]
Currently only tested on Ubuntu. Methinks [these lines](https://github.com/awerchniak/cdk-hiscores-tracker/commit/648d62e5d580b455149283cc04880abc9bf67e49#diff-f408df4e71d4f7f8a1bd2fa3d1bcbcaeef906f5a883f64fd7a7096563343f519R44-R48) may give some trouble when building on different OS's, since Lambda functions conveniently run in a Ubuntu container.

**Comment by awerchniak** [comment]
To address the above lines, I attempted to use the [aws-lambda-python module](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-python-readme.html), per [this StackOverflow answer](https://stackoverflow.com/a/69836646/5231520). Unfortunately, I don't believe that it supports CDK version 2. When I try to install the requirements after the updates in https://github.com/awerchniak/cdk-hiscores-tracker/commit/1aaeb2cdd919cc17fe823a32ea65db108539c778, it gives:

```
ERROR: aws-cdk-core 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-iam 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-cloudwatch 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-events 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-kms 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-s3 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-assets 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-s3-assets 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-logs 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-ssm 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-ec2 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-efs 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-signer 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-ecr 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-ecr-assets 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-autoscaling-common 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-applicationautoscaling 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-codeguruprofiler 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-sqs 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-lambda 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
ERROR: aws-cdk-aws-lambda-python 1.136.0 has requirement constructs<4.0.0,>=3.3.69, but you'll have constructs 10.0.12 which is incompatible.
```

Then, when I try to `cdk synth`, it fails with a related error:
```
(.venv) andyw@DESKTOP-Q0LKRM6:~/code/cdk-hiscores-tracker$ cdk synth
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    import aws_cdk as cdk
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/aws_cdk/__init__.py", line 21457, in <module>
    from . import aws_apigateway
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/aws_cdk/aws_apigateway/__init__.py", line 1239, in <module>
    from ..aws_certificatemanager import ICertificate as _ICertificate_c194c70b
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/aws_cdk/aws_certificatemanager/__init__.py", line 187, in <module>
    from ..aws_cloudwatch import (
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/aws_cdk/aws_cloudwatch/__init__.py", line 495, in <module>
    from ._jsii import *
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/aws_cdk/aws_cloudwatch/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.aws_iam._jsii
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/aws_cdk/aws_iam/__init__.py", line 504, in <module>
    from ._jsii import *
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/aws_cdk/aws_iam/_jsii/__init__.py", line 11, in <module>
    import aws_cdk.core._jsii
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/aws_cdk/core/__init__.py", line 6371, in <module>
    class ConstructNode(metaclass=jsii.JSIIMeta, jsii_type="@aws-cdk/core.ConstructNode"):
  File "/mnt/c/Users/andyw/code/cdk-hiscores-tracker/.venv/lib/python3.8/site-packages/aws_cdk/core/__init__.py", line 6553, in ConstructNode
    runtime_info: typing.Optional[aws_cdk.cx_api.RuntimeInfo] = None,
AttributeError: partially initialized module 'aws_cdk' has no attribute 'cx_api' (most likely due to a circular import)
```

**Comment by trevordavis** [comment]
I was able to get this to work on Windows, but there were a few additional configs I needed for AWS CLI.

First, I had to make a new group in the AWS console identity access management portal here: https://console.aws.amazon.com/iamv2/home?#/groups. I named this group "Admin" for clarity.

Then I had to give this group four permissions to enable cdk bootstrapping and deployment to work out of the box. These are:

- IAMFullAccess
- AWSCodeDeployFullAccess
- AdministratorAccess
- AWSCloudFormationFullAccess

It's possible that these permissions are a superset of what's strictly needed, and/or that another combination of permissions is compatible with the CDK deploy + bootstrapping process.

Then I created a new user in this group. My user is named after myself, but you can name it anything you like.

Lastly, I added two flags to the already-provided CLI commands for cdk bootstrapping + deployment. Adding `--profile <MyProfileName>` ensured I was using a profile other than default so I could get the right permissions. Adding `--trust <MyAccountID>`  ensured that the account itself was trusted to bootstrap the stack in question.

I believe that VS Code extensions for AWS CDK may preclude the need to add these command line options due to persisted permissions managed by the extension itself.

Another more manual option to avoid creating a profile in the AWS console portal is to use the --cloudformation-execution-policies flag to individually specify execution policies for your cdk command. IMO this is more cumbersome but potentially useful in edge cases where profile permissions may not be known or easily discoverable.

**Comment by awerchniak** [comment]
Thanks @trevordavis ! Excited to hear building worked on Windows. I just tried it on Mac and it also worked.

The steps you point out should be required for all platforms, and you laid them out well (just followed the exactly for my mac setup). I'll add them to the README!
